apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  # namespace: <ton-namespace-etudiant>  <-- ENLEVE CETTE LIGNE SI TU N'AS PAS DE NAMESPACE IMPOSÉ
type: Opaque
data:
  # Remplace ci-dessous par ton résultat base64
  DB_PASSWORD: YXJkYWxlZ29hdA==